// <auto-generated />
using System;
using MHStore.Repositories.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MHStore.Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701074605_SeedSampleData")]
    partial class SeedSampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MHStore.Repositories.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Name = "Món chính",
                            Slug = "mon-chinh",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Ăn vặt",
                            Slug = "an-vat",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("MHStore.Repositories.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address_note");

                    b.Property<string>("AddressReferenceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("address_reference_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerInfo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("customer_info");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("delivery_address");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("OrderChannel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_channel");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("order_code");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_status");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_status");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("receiver_name");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("receiver_phone");

                    b.Property<bool>("StockReleased")
                        .HasColumnType("boolean")
                        .HasColumnName("stock_released");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_price");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrderChannel");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("OrderStatus");

                    b.HasIndex("PaymentMethod");

                    b.HasIndex("PaymentStatus");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            AddressNote = "Giao sau 18h",
                            AddressReferenceId = "",
                            CreatedAt = new DateTime(2026, 6, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerInfo = "{\"name\":\"Anh Huy\",\"phone\":\"0334140131\",\"address\":\"Quận 1, TP.HCM\",\"latitude\":null,\"longitude\":null,\"note\":\"Giao sau 18h\",\"addressReferenceId\":\"\"}",
                            DeliveryAddress = "Quận 1, TP.HCM",
                            OrderChannel = "Website",
                            OrderCode = "MH26063044444444",
                            OrderStatus = "PendingConfirmation",
                            PaymentMethod = "Online",
                            PaymentStatus = "Pending",
                            ReceiverName = "Anh Huy",
                            ReceiverPhone = "0334140131",
                            StockReleased = false,
                            TotalPrice = 210000m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            AddressNote = "Đã thanh toán SePay",
                            AddressReferenceId = "",
                            CreatedAt = new DateTime(2026, 6, 29, 13, 0, 0, 0, DateTimeKind.Utc),
                            CustomerInfo = "{\"name\":\"Chị Minh\",\"phone\":\"0334140131\",\"address\":\"Quận Bình Thạnh, TP.HCM\",\"latitude\":null,\"longitude\":null,\"note\":\"Đã thanh toán SePay\",\"addressReferenceId\":\"\"}",
                            DeliveryAddress = "Quận Bình Thạnh, TP.HCM",
                            OrderChannel = "Website",
                            OrderCode = "MH26062944444444",
                            OrderStatus = "Completed",
                            PaymentMethod = "Online",
                            PaymentStatus = "Paid",
                            ReceiverName = "Chị Minh",
                            ReceiverPhone = "0334140131",
                            StockReleased = false,
                            TotalPrice = 250000m
                        });
                });

            modelBuilder.Entity("MHStore.Repositories.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777771"),
                            OrderId = new Guid("44444444-4444-4444-4444-444444444441"),
                            ProductId = new Guid("33333333-3333-3333-3333-333333333331"),
                            ProductName = "Chả ram tôm đất",
                            Quantity = 1,
                            UnitPrice = 120000m
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777772"),
                            OrderId = new Guid("44444444-4444-4444-4444-444444444441"),
                            ProductId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProductName = "Cá viên chiên",
                            Quantity = 2,
                            UnitPrice = 45000m
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777773"),
                            OrderId = new Guid("44444444-4444-4444-4444-444444444442"),
                            ProductId = new Guid("33333333-3333-3333-3333-333333333332"),
                            ProductName = "Nem chua rán",
                            Quantity = 2,
                            UnitPrice = 65000m
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777774"),
                            OrderId = new Guid("44444444-4444-4444-4444-444444444442"),
                            ProductId = new Guid("33333333-3333-3333-3333-333333333331"),
                            ProductName = "Chả ram tôm đất",
                            Quantity = 1,
                            UnitPrice = 120000m
                        });
                });

            modelBuilder.Entity("MHStore.Repositories.Entities.PaymentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawData")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("PaymentLogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            Amount = 250000m,
                            CreatedAt = new DateTime(2026, 6, 29, 13, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = new Guid("44444444-4444-4444-4444-444444444442"),
                            RawData = "Seed payment log",
                            Status = "Paid",
                            TransactionId = "SEED-SEPAY-0001"
                        });
                });

            modelBuilder.Entity("MHStore.Repositories.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222221"),
                            Description = "Gói đông lạnh, chiên nhanh là giòn.",
                            ImageUrl = "https://images.unsplash.com/photo-1604908177522-0403f218842b?auto=format&fit=crop&w=900&q=80",
                            IsAvailable = true,
                            Name = "Chả ram tôm đất",
                            Price = 120000m,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Hộp tiện lợi cho bữa ăn vặt tại nhà.",
                            ImageUrl = "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80",
                            IsAvailable = true,
                            Name = "Nem chua rán",
                            Price = 65000m,
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Đóng gói sẵn, phù hợp chiên hoặc thả lẩu.",
                            ImageUrl = "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=80",
                            IsAvailable = true,
                            Name = "Cá viên chiên",
                            Price = 45000m,
                            Stock = 50
                        });
                });

            modelBuilder.Entity("MHStore.Repositories.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666661"),
                            ImageUrl = "https://images.unsplash.com/photo-1604908177522-0403f218842b?auto=format&fit=crop&w=900&q=80",
                            ProductId = new Guid("33333333-3333-3333-3333-333333333331"),
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666662"),
                            ImageUrl = "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80",
                            ProductId = new Guid("33333333-3333-3333-3333-333333333332"),
                            SortOrder = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666663"),
                            ImageUrl = "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=80",
                            ProductId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("MHStore.Repositories.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "MHStore Admin",
                            PasswordHash = "PBKDF2-SHA256.100000.TUhTdG9yZUFkbWluU2VlZA==.ACC1yxE9bTR835zC2Kuy+pf+C5xgL43C/BtSYOfKpb4=",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MHStore.Repositories.Entities.OrderItem", b =>
                {
                    b.HasOne("MHStore.Repositories.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MHStore.Repositories.Entities.PaymentLog", b =>
                {
                    b.HasOne("MHStore.Repositories.Entities.Order", "Order")
                        .WithMany("PaymentLogs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MHStore.Repositories.Entities.Product", b =>
                {
                    b.HasOne("MHStore.Repositories.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MHStore.Repositories.Entities.ProductImage", b =>
                {
                    b.HasOne("MHStore.Repositories.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MHStore.Repositories.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MHStore.Repositories.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("PaymentLogs");
                });

            modelBuilder.Entity("MHStore.Repositories.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
